# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c6b40e309265de671b0c4390d6fb51b493d5d34dc3981ab1f99304e94d91a2342ad76a6e12efcdae512ef334ac87a223a76054d1481cc02af418bdf4833356b

test:
  secret_key_base: e431e7a0d1a798c302bff92219d06498ec3217ac9ff14c6a3e4ff43d1bb4e5ea9d9499d96cbce7f35b3c8647e13798787c545711da69e352ba53213f74cb762e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
